name: Code Quality

on:
  push:
    branches:
      - master
      - develop

jobs:
  codeQuality:
    runs-on: ubuntu-latest
    name: PHPCS
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install PHP and PHP Code Sniffer
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          tools: phpcs
      - name: Setup problem matcher for PHPCS
        run: echo "::add-matcher::${{ github.workspace }}/.github/workflows/matchers/phpcs-matcher.json"
      - name: Run code quality checks
        run: phpcs --colors -nq --report="checkstyle" --extensions="php" $(git show --name-only --pretty="" --diff-filter=ACMR ${{ github.sha }})
