name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  phpUnitTests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        phpVersions: ['7.2', '7.3', '7.4']
      fail-fast: false
    name: PHP ${{ matrix.phpVersions }}
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.phpVersions }}
          extension-csv: mbstring, intl, gd, xml, sqlite
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest --no-scripts
      - name: Run post-update Composer scripts
        run: |
          php artisan october:util set build
          php artisan package:discover
      - name: Run Linting and Tests
        run: |
          ./vendor/bin/parallel-lint --exclude vendor --exclude storage --exclude tests/fixtures/plugins/testvendor/goto/Plugin.php .
          ./vendor/bin/phpunit --prepend ./vendor/october/rain/src/Support/helpers.php
  duskTests:
    runs-on: ubuntu-latest
    name: PHP 7.3
    steps:
      - name: Checkout changes
        uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.3'
          extension-csv: mbstring, intl, gd, xml, sqlite
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-suggest --no-scripts
      - name: Run post-update Composer scripts
        run: |
          php artisan october:util set build
          php artisan package:discover
      - name: Install Chrome driver
        run: php artisan dusk:chrome-driver
      - name: Start Chrome driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &
      - name: Run Dusk Tests
        run: php artisan dusk
